import {
    Box,
    HStack,
    VStack,
    Text,
    Image,
    Avatar,
    AvatarFallbackText,
    View
} from '@gluestack-ui/themed'



export default function LeaderBoard() {

    return (
        <View
            width={'90%'}
        >
            <Box
                rounded={'$2xl'}
                justifyContent="center"
                alignItems="center"
                gap={'$2'}
                bgColor="$tertiaryBg"
                width={'100%'}
                padding={'$5'}
                py={'$6'}
            >
                <VStack
                    space={'md'}
                    justifyContent="center"
                    alignItems="center"
                    w={'100%'}
                >
                    <Box
                        justifyContent="center"
                        alignItems="center"
                        mb={'$2'}
                    >
                        <Image
                            source={require('../../../assets/crown.png')}
                            alt="Logo"
                            size="xs"
                            role="img"
                            mb={'$2'}
                        />
                        <Text
                            fontSize="$xl"
                            fontWeight="bold"
                            color="white"
                        >
                            LeaderBoard
                        </Text>
                    </Box>

                    <HStack
                        justifyContent="center"
                        alignItems="center"
                        w={'100%'}
                        gap={'$2'}
                    >
                        <Box
                            justifyContent="center"
                            alignItems="center"
                            alignSelf="flex-end">
                            <Avatar
                                alignSelf="center"
                                mb={'$4'}
                            >
                                <AvatarFallbackText>Two</AvatarFallbackText>
                            </Avatar>
                            <Text
                                mb={'$4'}
                                color="white"
                            >
                                Player Two
                            </Text>
                            <Image
                                source={require('../../../assets/leaderboard/leaderboard-2.png')}
                                alt="Leaderboard-2"
                                width={70}
                                height={35}
                                role="img"
                            />
                        </Box>

                        <Box
                            justifyContent="center"
                            alignItems="center"
                            alignSelf="flex-end">
                            <Avatar
                                alignSelf="center"
                                mb={'$6'}
                            >
                                <AvatarFallbackText>Player One</AvatarFallbackText>
                            </Avatar>
                            <Text
                                mb={'$5'}
                                color="white"
                            >
                                PlayerOne
                            </Text>
                            <Image
                                source={require('../../../assets/leaderboard/leaderboard-1.png')}
                                alt="Leaderboard-1"
                                width={70}
                                height={45}
                                role="img"
                            />
                        </Box>
                        <Box
                            justifyContent="center"
                            alignItems="center"
                            alignSelf="flex-end">
                            <Avatar
                                alignSelf="center"
                                mb={'$4'}
                            >
                                <AvatarFallbackText>Three</AvatarFallbackText>
                            </Avatar>
                            <Text
                                mb={'$5'}
                                color="white"
                                size='sm'
                            >
                                Player Three
                            </Text>
                            <Image
                                source={require('../../../assets/leaderboard/leaderboard-3.png')}
                                alt="Leaderboard-3"
                                width={70}
                                height={28}
                                role="img"
                            />
                        </Box>
                    </HStack>
                    {/* UserList */}
                    <Box
                        width={'100%'}
                        display='flex'
                        flexDirection='column'
                        gap={'$2'}
                    >
                        {/* Player 1 */}
                        <Box
                            justifyContent='flex-start'
                            alignItems="center"
                            flexDirection='row'
                            width={'100%'}
                            bg='$primaryBg'
                            rounded={'$2xl'}
                            gap={'$2'}
                            padding={'$2'}
                        >
                            <Text
                                color="white"
                                fontWeight="bold"
                                fontSize="$lg"
                                rounded={'$full'}
                                padding={'$1'}
                                bg='orange'
                                width={'11%'}
                                textAlign="center"
                            >
                                4
                            </Text>
                            <Avatar
                                alignSelf="center"
                                ml={'$2'}
                                bg='red'
                            >
                                <AvatarFallbackText>Guswandi</AvatarFallbackText>
                            </Avatar>
                            <Text
                                color="white"
                            >
                                Guswandi
                            </Text>
                        </Box>
                        {/* Player 1 */}
                        <Box
                            justifyContent='flex-start'
                            alignItems="center"
                            flexDirection='row'
                            width={'100%'}
                            bg='$primaryBg'
                            rounded={'$2xl'}
                            gap={'$2'}
                            padding={'$2'}
                        >
                            <Text
                                color="white"
                                fontWeight="bold"
                                fontSize="$lg"
                                rounded={'$full'}
                                padding={'$1'}
                                bg='orange'
                                width={'11%'}
                                textAlign="center"
                            >
                                5
                            </Text>
                            <Avatar
                                alignSelf="center"
                                ml={'$2'}
                                bg='red'
                            >
                                <AvatarFallbackText>G One The</AvatarFallbackText>
                            </Avatar>
                            <Text
                                color="white"
                            >
                                Wandi
                            </Text>
                        </Box>
                    </Box>
                </VStack>
            </Box>
        </View>
    )
}